server:
  port: ${RTD_TRANSACTION_ERROR_MANAGER_PORT:8080}
  tomcat:
    connection-timeout: ${RTD_TRANSACTION_ERROR_MANAGER_SERVER_CONNECTION_TIMEOUT:${SERVER_CONNECTION_TIMEOUT:}}
    max-connections: ${RTD_TRANSACTION_ERROR_MANAGER_SERVER_MAX_CONNECTION:${SERVER_MAX_CONNECTION:8192}}
    processor-cache: ${RTD_TRANSACTION_ERROR_MANAGER_SERVER_PROCESSOR_CACHE:${SERVER_PROCESSOR_CACHE:200}}
    threads.max: ${RTD_TRANSACTION_ERROR_MANAGER_SERVER_THREAD_MAX:${SERVER_THREAD_MAX:200}}
    threads.min-spare: ${RTD_TRANSACTION_ERROR_MANAGER_SERVER_THREAD_MIN:${SERVER_THREAD_MIN:10}}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable italian documentations
      - swaggerIT

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.fa.transaction_error_manager: ${LOG_LEVEL_FA_TRANSACTION_ERROR_MANAGER:DEBUG}