apiVersion: apps/v1
kind: Deployment
metadata:
  name: famstransactionerrormanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: famstransactionerrormanager
  template:
    metadata:
      labels:
        app: famstransactionerrormanager
    spec:
      containers:
        - name: famstransactionerrormanager
          image: cstardacr.azurecr.io/famstransactionerrormanager
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: application-insights
            - configMapRef:
                name: famstransactionerrormanager
            - secretRef:
                name: famstransactionerrormanager
            - configMapRef:
                name: eventhub-common